micronaut:
  application:
    name: dailyscrum
  security:
    enabled: false
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
datasources.default: {
  }
