micronaut:
  application:
    name: dailyscrum
  security:
    enabled: false
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
datasources:
  default:
    url: 'jdbc:postgresql://localhost/postgres'
    username: 'postgres'
    password: 'zaqwer'
    driverClassName: 'org.postgresql.Driver'
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
      drop-first: false
kotlin.exposed: "dsl"


